// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2826i1TkoNZHQ-GVZ21CCezZr4R_3_pc',
    appId: '1:87371512549:web:25a496aad985a3aeccb20c',
    messagingSenderId: '87371512549',
    projectId: 'smartbag-db5f6',
    authDomain: 'smartbag-db5f6.firebaseapp.com',
    storageBucket: 'smartbag-db5f6.appspot.com',
    measurementId: 'G-H8EMBM45GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiMemO1XVtYw_8o_AaFsneIdIUvYcWAwo',
    appId: '1:87371512549:android:7050c837b2c01e65ccb20c',
    messagingSenderId: '87371512549',
    projectId: 'smartbag-db5f6',
    storageBucket: 'smartbag-db5f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3HYz2oyokGQzpSMZEKYK_a3Ym1xf7LO4',
    appId: '1:87371512549:ios:7e757b50a06df80dccb20c',
    messagingSenderId: '87371512549',
    projectId: 'smartbag-db5f6',
    storageBucket: 'smartbag-db5f6.appspot.com',
    iosClientId: '87371512549-fumn8o8mgua9kj55gc8uut8979d2cfv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartBagm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3HYz2oyokGQzpSMZEKYK_a3Ym1xf7LO4',
    appId: '1:87371512549:ios:7e757b50a06df80dccb20c',
    messagingSenderId: '87371512549',
    projectId: 'smartbag-db5f6',
    storageBucket: 'smartbag-db5f6.appspot.com',
    iosClientId: '87371512549-fumn8o8mgua9kj55gc8uut8979d2cfv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartBagm',
  );
}
